=== Ollenino/webbteknik_3/Uppgift1/Songlist.dtd
<!---
Songlist
-   Genre+ 
    - Hiphop
        -Intance
            - Song: Juicy -The notorious B.I.G.
            - Artist: Eminem
    - Classic
        - Instance
            - Song: Canon i D - Pachelbel
            - Artist: Mozart
    - Pop
        - Instance
            - Song: Thriller - Michael Jackson
            - Artist: Ed Sheeran
    - House
        -Instance
            - Song: Levels - Avicii
            - Artist: David Guetta
-->

<!ELEMENT Songlist (Genre+)>
<!ELEMENT Genre (Instance+)>
<!ATTLIST Genre name CDATA #REQUIRED>

<!ELEMENT Instance (Song, Artist)>
<!ATTLIST Instance id ID #REQUIRED>

<!ELEMENT Song (#PCDATA)>
<!ATTLIST Song url CDATA #IMPLIED>

<!ELEMENT Artist (#PCDATA)>

=== Ollenino/webbteknik_3/Uppgift1/songlist_classical.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Songlist SYSTEM "songlist.dtd">
<Songlist>
    <Genre name="Classical">
        <Instance id="c1">
            <Song url="https://open.spotify.com/track/1c3GkbZBnyrQ1cm4TGHFrK?si=37655db5141049bc">Canon in D</Song>
            <Artist>Pachelbel</Artist>
        </Instance>
        <Instance id="c2">
            <Song url="https://open.spotify.com/track/1DfGPEHxTYeaJpiNA4xUb5?si=5437002a0b3b4acc">FÃ¼r Elise</Song>
            <Artist>Ludwig van Beethoven</Artist>
        </Instance>
    </Genre>
</Songlist>

=== Ollenino/webbteknik_3/Uppgift1/songlist_hiphop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Songlist SYSTEM "songlist.dtd">
<Songlist>
    <Genre name="Hiphop">
        <Instance id="s1">
            <Song url="https://open.spotify.com/track/2b7FqlHc3JrzlYtGEkzq22?si=1a0e4f3853dd48ee">Juicy</Song>
            <Artist>The Notorious B.I.G.</Artist>
        </Instance>
        <Instance id="s2">
            <Song url="https://open.spotify.com/track/5Z01UMMf7V1o0MzF86s6WJ?si=89885910f5fc4dc2">Lose Yourself</Song>
            <Artist>Eminem</Artist>
        </Instance>
    </Genre>
</Songlist>
